### ISSUE TITLE
Cosmicjs template in a folder

### ISSUE THREAD

**Issue by josbroers** [cosmicjs/gridsome-source-cosmicjs#4]
I want to create the following url's:

`/speltakken/bevers/post1`
`/speltakken/bevers/post2`
`/speltakken/bevers/post3`

I created the object type `Bevers`, created the folder `speltakken` inside the `template` folder and added this file: `CosmicjsBevers.vue`.  I expect that when I run `gridsome develop` or `gridsome build` the files generated by  `CosmicjsBevers.vue` will be added to the `speltakken` folder inside the `bevers` folder. But instead nothing happens.

Is there a way to achieve this in another way?

**Comment by josbroers** [comment]
@tonyspiro You have any idea?

**Comment by jazibsawar** [comment]
@sir-red-dab for now, it is not possible to create the url's you mentioned. But you can fork and change the path here: https://github.com/cosmicjs/gridsome-source-cosmicjs/blob/6bad89b70856f7c653058fdc55021a39d643b5fc/index.js#L48

**Comment by josbroers** [comment]
> @sir-red-dab for now, it is not possible to create the url's you mentioned. But you can fork and change the path here:
> 
> https://github.com/cosmicjs/gridsome-source-cosmicjs/blob/6bad89b70856f7c653058fdc55021a39d643b5fc/index.js#L48

Thanks for the reply.
